### ISSUE TITLE
Add support for python 2

### ISSUE THREAD

**Issue by mhib** [jajakobyly/silnia#2]
Here is the error code:
➜  silnia git:(master) python --version        
Python 2.7.6
➜  silnia git:(master) python silnia.py 3 4.txt
  File "silnia.py", line 7
SyntaxError: Non-ASCII character '\xc4' in file silnia.py on line 7, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by jajakobyly** [comment]
I have no plans to support Python 2
